spring:
  application:
    name: jarvis
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      model: gpt-4o-mini
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 30MB

api:
  timeout:
    connect: 10000
    read: 30000

server:
  port: 8080